name: Network Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  check_network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Network Connectivity
        run: |
          IP_ADDRESS="your_home_ip_here"
          LOG_FILE="docs/network_log.csv"
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

          # Create CSV file with headers if it doesn't exist
          if [ ! -f "$LOG_FILE" ]; then
            echo "timestamp,uptime" > "$LOG_FILE"
          fi

          # Check network status and log it
          if ping -c 1 "$IP_ADDRESS" > /dev/null; then
              STATUS="100"  # Convert "up" to 100 for Chart.js
          else
              STATUS="0"  # Convert "down" to 0
          fi
          
          echo "$TIMESTAMP,$STATUS" >> "$LOG_FILE"

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git pull --rebase  # Prevent conflicts with remote updates
          
          git add docs/network_log.csv
          git commit -m "Updated network uptime log" || exit 0
          git push
