name: Network Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Network Connectivity
        run: |
          IP_ADDRESS="154.56.232.180"
          LOG_FILE="docs/network_log.csv"
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

          if [ ! -f "$LOG_FILE" ]; then
            echo "timestamp,status" > "$LOG_FILE"
          fi

          if ping -c 1 "$IP_ADDRESS" > /dev/null; then
              STATUS="up"
          else
              STATUS="down"
          fi
          
          echo "$TIMESTAMP,$STATUS" >> "$LOG_FILE"

      - name: Install Python & Generate Chart
        run: |
          sudo apt-get install -y python3 python3-pip
          pip install pandas matplotlib
          python <<EOF
          import pandas as pd
          import matplotlib.pyplot as plt

          df = pd.read_csv("docs/network_log.csv")
          df['timestamp'] = pd.to_datetime(df['timestamp'])
          df['status'] = df['status'].map({'up': 1, 'down': 0})

          plt.figure(figsize=(12, 6))
          plt.plot(df['timestamp'], df['status'], drawstyle="steps-post", label="Uptime", color='green')
          plt.xlabel("Time")
          plt.ylabel("Status")
          plt.title("Network Uptime History")
          plt.yticks([0, 1], ["Down", "Up"])
          plt.legend()
          plt.grid()
          plt.savefig("docs/network_uptime_chart.png")
          EOF

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Updated network uptime data and chart" || exit 0
          git push
