name: Network Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  check_network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Check Network Connectivity
        run: |
          IP_ADDRESS="154.56.232.180"
          LOG_FILE="docs/network_log.csv"
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

          # Create CSV file with headers if it doesn't exist
          if [ ! -f "$LOG_FILE" ]; then
            echo "timestamp,uptime" > "$LOG_FILE"
          fi

          # Check network status and log it
          if curl -s --head --request GET http://$IP_ADDRESS | grep "nginx" > /dev/null; then
              STATUS="100" # Up
          else
              STATUS="0"  # Down
          fi
          
          echo "$TIMESTAMP,$STATUS" >> "$LOG_FILE"

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          git add -A  # Stage all changes
          git commit -m "Updated network uptime log" || exit 0
      
          # Ensure the latest changes are fetched and rebased
          git pull --rebase --autostash origin main
      
          git push
