name: Network Monitor

on:
  push:
    branches:
      - main

jobs:
  update-network-uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run network status plot
        run: |
          python plot_network.py

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Stash changes
        run: |
          git stash

      - name: Pull remote changes
        run: |
          git pull --rebase

      - name: Apply stashed changes
        run: |
          git stash pop || true

      - name: Commit and push changes
        run: |
          git add docs/
          git commit -m "Updated network uptime data and chart" || exit 0
          git push
